[tool.poetry]
name = "frontier-proj"
version = "0.1.0"
description = ""
authors = ["r-silos <r.silos36@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
